### ISSUE TITLE
Unable to build the image

### ISSUE THREAD

**Issue by age-77** [DeBaschdi/docker.solaranzeige#1]
Error occurs during build the image form Dockerfile.arm64v8

Step 10/21 : COPY root/qemu-aarch64-static /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder511545601/root/qemu-aarch64-static: no such file or directory

**Comment by DeBaschdi** [comment]
This Image can be build from hub.docker.com directly,
hub.docker call some hooks pre / post build.
E.g 
https://github.com/DeBaschdi/docker.solaranzeige/blob/master/hooks/post_checkout
