### ISSUE TITLE
Unraid Docker WebUi not available

### ISSUE THREAD

**Issue by Nexus1212** [DeBaschdi/docker.solaranzeige#14]
Hi, 
the webUI is not available on unraid docker.

I run the docker image via Unraid Template:
https://raw.githubusercontent.com/DeBaschdi/docker.solaranzeige/master/Templates/Unraid/my-Solaranzeige.xml 

Grafana, Influx and Apache (IP-Server+:Port) are not available. 

Is there a hint in setup or a problem with the image?

best regards

**Comment by DeBaschdi** [comment]
please take a look at your container log and let us know whats going up. -->  https://solaranzeige.de/phpBB3/viewforum.php?f=35
