### ISSUE TITLE
How to restore influx database inside container?

### ISSUE THREAD

**Issue by jotrocken** [DeBaschdi/docker.solaranzeige#16]
Hallo,

I used Solaranzeige for a few years on a RPi (w/o Docker). Now I want to import my influx database into this docker container, but how and **when** has this to be done?
When I restore the influxdb before running the setup script, then the database will be overwritten. But importing after that isn't working because there is no import possibility into _existing_ databases, see [influx docs](https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/#restore-data-to-an-existing-database). I tried to use a temporary database as described in the documentation, but it didn't work either.
Has anyone of you successfully imported it's old database backup?

Or is it another way **not** to use a official backup created with `influxd backup ...` but simply to copy the folder `/var/lib/influxdb` (or any other?) into the container volume?

**Comment by DeBaschdi** [comment]
Hi, just override your exported influx folder with that one from your rpi.
Same u can do with grafana.

**Comment by jotrocken** [comment]
Thanks, Baschdi. So you mean mounting the entire content of the RPi directories  `/var/lib/influxdb` and `/var/lib/grafana` int the new Docker-Solaranzeige? Before or after running setup? Or no setup running at all?

**Comment by DeBaschdi** [comment]
After container is set up, after copying, restart




Jonas ***@***.***> schrieb am Mo., 1. Mai 2023, 18:33:
