### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by trickert76** [DeBaschdi/docker.solaranzeige#19]
...ich schreib mal auf deutsch, weil is ja irgendwie typisch deutsch...

Ich probier das gerade alles aus und mir sind gleich zwei Sachen aufgefallen. Wenn ich das zum Laufen bringe hier, kann ich da gerne auch nachhelfen mit Pullrequests. Aber erstmal die Ansätze

- Ein Docker Container für alles ist zwar sicher für die meisten toll einfach, aber irgendwie nicht docker. Ich würde das trennen wollen, allein schon, weil gibt ja evtl. schon laufende Grafanas etc. Wie siehst Du das?
- die Erstinstallation via Shell könnte man doch eigentlich auch dadurch lösen, dass man die ganzen PHP Variablen in ENV-Vars steckt und im Docker-Entrypoint dann ersetzt. ich hab noch nicht in die Details geschaut, aber dann wäre das Ding "sofort" einsatzbereit und auch irgendwie mehr Docker-Like.
- weiß jemand, welcher Lizenz hintr den Solaranzeige PHP Scripten liegt
- ein healthcheck müsste eigentlich auch umsetzbar sein (als eigener PHP Script)

Auf jeden Fall Danke fürs zusammentragen des Docker Images. War ein Haufen Arbeit, wenn ich mir das Forum anschaue.

**Comment by DeBaschdi** [comment]
Hi, ja absolut.
Das Image ist bzw soll DAU tauglich sein, wer kein Influx / Mosquitto drin haben will muss eben ein eigenes bauen, immerhin besteht die Möglickeit diese Dienste garnicht erst in meinem Image zu starten, das gleiche könnte ich für Grafana noch umsetzen.

Bezüglich der ENV Vars für das Regler Setup, vergiss es, viel zu Umfangreich und bläst das ganze ungemein auf, insbesondere wenn Multiregler umgesetzt werden soll. :D

Health Check ist etwas tricky, zuverlässig mach ich das auf Host Seite, innerhalb des Images können beim Auslesen in Dauerschleife Probleme auftreten, sofern das passiert, startet mein Host das Image neu.

**Comment by trickert76** [comment]
ok, das klingt eher nach einem: "ne lass ma". Ich hab mal geforkt und probier etwas rum. Muss erstmal die ganzen Scripte verstehen. Meld mich mit nem Branch, wenns läuft. Merge wirds aber schwierig. Ich bau das ziemlich um und muss ein paar alt Zöpfe abschneiden (bsp: wozu ein SSH server installiert wird, bzw. es gibt fertige PHP7.4 Docker base images, oder warum die Konfig von Github beim Start nachgeladen wird).

**Comment by DeBaschdi** [comment]
Diesbezüglich z.b, da Ulrich diesen Zugang für Fernwartungen Nutzt (wie im rpi image).

**Comment by trickert76** [comment]
So, ich hab mir das mal länger angeschaut. 

Ich nenne das mal diplomatisch ein gewachsener Projekt....

Der PHP Code ist echt hui. Man kann richtig erkennen, wie Feature um Feature dazukam und die Erfahrung anwuchs.

Ich werde das aber komplett anders machen, also auch den PHP Code umbauen. Funktionen wie der Fernzugriff gehören da nicht rein und das Update macht das Docker-Image (dann gibt es halt eine neue Version) und nicht der Code selber. Ich weiß, Du wolltest erstmal einfach nur einen Container haben. Das funktioniert auch.

Ulrich hat an einigen Stellen im Code von GPL3 geschrieben, insofern ist in meinen Augen eine Weiterentwicklung und Code-Hosting erlaubt. Das wird aber eh ein harter Fork, weil der Code nicht mehr kompatibel sein wird. Ich werde das mal für meine Sungrow hier fertig machen und dann schick ich einen Link rum.

**Comment by trickert76** [comment]
Achso, Thema ENV Variablen verwenden. Einfaches Beispiel mit einer Funktion, die via getenv schaut, ob eine Variable gesetzt ist und diese dann zurückgibt oder ein Defaultwert

```
function getEnvAsString(string $key, string $defaultValue) :string {
  $value = getenv($key);
  if ($value === FALSE) return $defaultValue;
  return $value;
}
```

Und dann ersetzen wir 

```
$WR_IP = "0.0.0.0";
```

mit

```
$WR_IP = getEnvAsString("SA_WR_IP","0.0.0.0");
```

etc. pp und sind das Problem los, dass man mit mcedit da rumfummeln muss. Bei den Multi-Dingern kann man noch eine For-oder While-Schleife nehmen und einen Counter oder so in den Key einbauen und fertig ist man. Das waren jetzt 30-40 Stellen inkl. Defaultwerte. Typisierung mit entsprechend angepassten Methoden (bool, float, integer)

**Comment by trickert76** [comment]
Zur Info: Ich bin mit dem Refactoring noch nicht entgültig zufrieden, aber es läuft schon mal bei mir (ohne Steuerung) für eine Sungrow. Die anderen kann ich nicht testen. Siehe https://github.com/trickert76/docker.solaranzeige/tree/sungrow

- docker-compose Beispiel mit Grafana, InfluxDB (leider geht nur 1.8) und Solaranzeige
- Grafana und InfluxDB werden provisioniert
- Grafana wird durch den Solaranzeige Apache durchgeproxiet, kein anderer Port notwendig
- Solaranzeige hab ich den PHP Code komplett umgestrickt auf mehrere Verzeichnisse und so weiter
- Konfiguration in der .env Datei. Beispiel liegt bei.

Was noch nicht geht

- Multiple Devices. Ich will da in Zukunft keinen Unterschied machen, ob 1 oder x Devices. Das kann ich im Moment aber noch nicht testen
- alles außer Sungrow hab ich nicht getestet
- PVForecast hab ich nicht getestet
- MQTT hab ich nicht getestet

Was noch fehlt

- die ganzen Wechselrichter Konfigs in Klassen packen und selber registrieren und statt ner Nummer X den Namen angeben
- die Custom-PHP-Scripts in ein Volume packen, genauso die Config und dann prüfen, ob da und wenn nein, anlegen
- sinnvolle Dokumentation
- Ulrich fairerweise Bescheid geben, aber es steht überall GPL3, muss ich nur noch überall erwähnen
- die Klassen besser aufbauen (autoloader ist schon da, aber die Klassen sind statisch
- viel zu viele globale Variablen, die mit Sicherheit noch jede Menge Fehler produzieren, weil sie nicht global geladen werden

**Comment by DeBaschdi** [comment]
Nimms mir nicht krumm, sehe aber kein Licht bei dir am Ende des Tunnels,
den Support kannst du nicht leisten sobald du das Rad neu erfindest.

Ich selbst habe eine Multiregler, energymeter, stp10 se, stp x15 , also 3
Geräte mit unterschiedlichen Parametern.




Thoralf Rickert-Wendt ***@***.***> schrieb am Mi., 21. Juni
2023, 19:09:

**Comment by trickert76** [comment]
Was interessiert mich persönlich der Support. Ich hab ein Problem damit, dass der Code so versteckt wird und das der nur für Raspberry geht, den ich nicht einsetzen will (oder zumindest nicht das Image). Und wenn man dann wie Du fragt, ob man das anders machen kann, wird man fast schon abgewiesen (auf jeden Fall empfand ich die Antworten von Ulrich einsilbig und unfreundlich). Allein das schreckt ab.

Wenn der Code offen liegt, man entsprechende Pipelines hat und ja, auch mit Docker hat man eine definierte Umgebung gibt es definitiv mehr Leute, die helfen können. Man kann auch wie Github Actions Raspberry Images bauen, kann alles auf dem gleichen Repo aufbauen, wenns sein muss. Und um ehrlich zu sein, sind die Abhängigkeiten mit einem Docker-Container zum drum-herum des Raspi deutlich geringer.

Klar, der Null-Acht-15 Hausbesitzer ohne IT Erfahrung sucht ein Tool, mit dem er was sehen und steuern kann. Wenn er kein Bock hat, Geld auszugeben (weil das gibt es alles mittlerweile aus einem Guss) muss er basteln. Wenn er Fragen hat, soll er das tun. Warum muss ich der Einzige sein, der ihm antwortet - wenn man in (gut verständlichen) Code schaut, sieht man, wie es läuft.

Ich weiß nicht, warum Ulrich da so verschlossen ist. Wenn mehr Leute sehen, was im Code passiert, können auch mehr Leute helfen, so skaliert das und nicht darüber die Umgebung einzugrenzen und sich einzuigeln.

Ich erwarte keinen Support von Ulrich oder Dir, ich (als Null-Acht-15) hoffe(!) auf Hilfe durch die Community. Nicht mehr, nicht weniger.

Mir reicht es, wenns bei mir läuft.

Sorry - das musste raus.
