### ISSUE TITLE
docker exec -ti Solaranzeige /solaranzeige/setup nicht vorhanden

### ISSUE THREAD

**Issue by domib97** [DeBaschdi/docker.solaranzeige#3]
`starting container process caused: exec: "/solaranzeige/setup": stat /solaranzeige/setup: no such file or directory: unknown
`
Habe dann in den /solaranzeige ordner im docker geschaut und da ist nur ein leerer config ordner. Wo ist die setup datei?

**Comment by DeBaschdi** [comment]
Possible Fix for RPI :
https://solaranzeige.de/phpBB3/viewtopic.php?p=9588#p9588
