### ISSUE TITLE
influxdb not starting up automatically

### ISSUE THREAD

**Issue by Schriazugul** [DeBaschdi/docker.solaranzeige#6]
it looks like influxdb isn't set up to autostart.
i had to manually "service start influxdb" to get things to work properly.

**Comment by DeBaschdi** [comment]
Are u using Environment -e INFLUXDB="yes" ? 
Can u check this ?
Pls also check /var/www/log/solaranzeige.log

**Comment by Schriazugul** [comment]
> Are u using Environment -e INFLUXDB="yes" ?

yes i do

>  Pls also check /var/www/log/solaranzeige.log

`23.05. 09:35:01 |----------------   Start  fronius_symo_serie.php    ---------------
23.05. 09:35:01    -API Version: 1 CompatibilityRange: 1.7-4
23.05. 09:35:01    -Modell = Fronius GEN 24
23.05. 09:35:01 *  -Daten zur lokalen InfluxDB [ solaranzeige ] gesendet.
23.05. 09:35:55    -OK. Datenübertragung erfolgreich.
23.05. 09:35:55 |----------------   Stop   fronius_symo_serie.php    ---------------
`
log looks good, application & influxdb are working fine, it's just not starting up automatically

**Comment by DeBaschdi** [comment]
If influx were stopped, you cant send data.

**Comment by Schriazugul** [comment]
it is only working because i manually did a "service start influxdb" within the container. 
if i hadn't done this it would of course show me errors in the log

**Comment by DeBaschdi** [comment]
So, pls do a normal start and check what i said.

M.f.G
Bastian Kleinschmidt
Lichtenberger Str.13
64405 Fischbachtal/ Lichtenberg
0160 / 3050453



Schriazugul ***@***.***> schrieb am Mo., 23. Mai 2022, 13:34:
