### ISSUE TITLE
No data received from inverter after reboot

### ISSUE THREAD

**Issue by le-synchrotron** [DeBaschdi/docker.solaranzeige#7]
Hi,

when my SBC restarts, docker image (called "solaranzeige") is also started and everything seems to work fine, but i get no data from the inverter, every minute it runs "auslesen"-script and writes 0 (zero) in all influxdb columns.
(influxdb is started automatically, of course)

I stop the docker image and start a "solaranzeige_test" image with same parameters (ports, influxdb restart yes, etc.)  wait for some minutes and "solaranzeige_test" shows all data (voltage, power of PV, consumption, etc.).
I stop "solaranzeige_test" and restart "solaranzeige" and after some minutes, it reads all data from inverter.
I tried to setup multiple times the dockerimage on Raspberry Pi3, Orangepi PC2 and Pine64, it is always same behaviour.
I also tried the original image from solaranzeige with my Pi3; i can do whatever i want, hard reset, soft reset, killing some processes, whatever, after restart, it reads all data from inverter.

Any suggestions? logfiles are okay, no errors, just 0 0 0 0 0 (watt, voltage,ampers, whatever) in my database.

Regardes

**Comment by DeBaschdi** [comment]
Puh,
maybe u can try to switch bridge >----< hostmode
