### ISSUE TITLE
grafana.ini

### ISSUE THREAD

**Issue by gnoffer** [DeBaschdi/docker.solaranzeige#9]
Hi, i wanted to change some settings on grafana.ini but after containerrestart it will be resest to default.
i tried to mount that file from host with :ro option but that brings the container to crash at boot.

settings i want to set:
`allow_embedding = true
auth.anonymous
enabled = true`

**Comment by DeBaschdi** [comment]
Hi, please edit files here, after that, restart your Container :)

https://solaranzeige.de/phpBB3/viewtopic.php?p=21298#p21298

standart password for fileeditor is "solar"

**Comment by gnoffer** [comment]
yes, just got it working. sorry for bothering. have a nice weekende!
